services:
  # Aplikasi API Forum
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      # Database produksi
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGHOST: "postgres-db"
      PGPORT: "${PGPORT}"
      PGDATABASE: "${PGDATABASE}"
      # Database test (untuk referensi dalam aplikasi)
      PGUSER_TEST: "${PGUSER_TEST}"
      PGPASSWORD_TEST: "${PGUSER_PASS}"
      PGHOST_TEST: "postgres-test"
      PGPORT_TEST: "${PGPORT_TEST}"
      PGDATABASE_TEST: "${PGDATABASE_TEST}"
      # JWT Token
      ACCESS_TOKEN_KEY: "${ACCESS_TOKEN_KEY}"
      REFRESH_TOKEN_KEY: "${REFRESH_TOKEN_KEY}"
      ACCCESS_TOKEN_AGE: "${ACCCESS_TOKEN_AGE}"
    env_file:
      - .env
    depends_on:
      postgres-db:
        condition: service_healthy
      postgres-test:
        condition: service_healthy
    command: >
      sh -c "
        npm run migrate:test up &&
        npm run migrate up &&
        npm run start"
    networks:
      - forum-network
    restart: unless-stopped

  # Database Produksi
  postgres-db:
    image: postgres:15.13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGDATABASE: "${PGDATABASE}"
      PGPORT: "${PGPORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db-prod.sh:/docker-entrypoint-initdb.d/init-db-prod.sh:ro
    ports:
      - "${PGPORT}:5432"
    networks:
      - forum-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${PGDATABASE} -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s

  # Database Test
  postgres-test:
    image: postgres:15.13
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGUSER_TEST: "${PGUSER_TEST}"
      PGUSER_PASS: "${PGUSER_PASS}"
      PGDATABASE_TEST: "${PGDATABASE_TEST}"
      PGPORT_TEST: "${PGPORT_TEST}"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
      - ./init-db-test.sh:/docker-entrypoint-initdb.d/init-db-test.sh:ro
    ports:
      - "5433:5432"
    networks:
      - forum-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${PGDATABASE_TEST} -h localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s

volumes:
  postgres-data:
    name: forum-postgres-data
  postgres-test-data:
    name: forum-postgres-test-data

networks:
  forum-network:
    name: forum-network
    driver: bridge
