services:
  # Aplikasi API Forum
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      # Database produksi
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGHOST: "${PGHOST}"
      PGPORT: "${PGPORT}"
      PGDATABASE: "${PGDATABASE}"
      # Database test (untuk referensi dalam aplikasi)
      PGUSER_TEST: "${PGUSER_TEST}"
      PGPASSWORD_TEST: "${PGUSER_PASS}"
      PGHOST_TEST: "postgres-test"
      PGPORT_TEST: "${PGPORT_TEST}"
      PGDATABASE_TEST: "${PGDATABASE_TEST}"
      # JWT Token
      ACCESS_TOKEN_KEY: "${ACCESS_TOKEN_KEY}"
      REFRESH_TOKEN_KEY: "${REFRESH_TOKEN_KEY}"
      ACCCESS_TOKEN_AGE: "${ACCCESS_TOKEN_AGE}"
    env_file:
      - .env
    command: >
      sh -c "
        npm run migrate:test up &&
        npm run migrate up &&
        npm run start"
    networks:
      - forum-network
    restart: unless-stopped

networks:
  forum-network:
    name: forum-network
    driver: bridge
