services:
  # Aplikasi API Forum
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forum-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      # Database produksi
      PGUSER: "${PGUSER}"
      PGPASSWORD: "${PGPASSWORD}"
      PGHOST: "${PGHOST}"
      PGPORT: "${PGPORT}"
      PGDATABASE: "${PGDATABASE}"
      # Database test (untuk referensi dalam aplikasi)
      PGUSER_TEST: "${PGUSER_TEST}"
      PGPASSWORD_TEST: "${PGPASSWORD_TEST}"
      PGHOST_TEST: "PGHOST_TEST"
      PGPORT_TEST: "${PGPORT_TEST}"
      PGDATABASE_TEST: "${PGDATABASE_TEST}"
      # JWT Token
      ACCESS_TOKEN_KEY: "${ACCESS_TOKEN_KEY}"
      REFRESH_TOKEN_KEY: "${REFRESH_TOKEN_KEY}"
      ACCCESS_TOKEN_AGE: "${ACCCESS_TOKEN_AGE}"
    env_file:
      - .env
    command: >
      sh -c "
        echo 'Starting container...' &&
        echo 'Running migrations (ignoring errors if tables exist)...' &&
        (npm run migrate:test up || echo 'Test migration failed or already applied') &&
        (npm run migrate up || echo 'Production migration failed or already applied') &&
        echo 'Starting application...' &&
        npm run start"
    networks:
      - forum-network
    restart: unless-stopped

networks:
  forum-network:
    name: forum-network
    driver: bridge
