# Workflow ini akan melakukan build dan testing terhadap development app.
name: Dev Testing 🔎

on:
  pull_request:
    branches: ["main"]

jobs:
  build-testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "# HTTP SERVER" > .env
          echo "PORT=${{ secrets.APP_PORT }}" >> .env

          echo "# Database Production" >> .env
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.DB_DBNAME }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.DB_PORT }}" >> .env

          echo "# Database Test"
          echo "POSTGRES_USER_TEST=${{ secrets.DB_USER_TEST }}" >> .env
          echo "POSTGRES_PASSWORD_TEST=${{ secrets.DB_PASSWORD_TEST }}" >> .env
          echo "POSTGRES_DB_TEST=${{ vars.DB_DBNAME_TEST }}" >> .env
          echo "POSTGRES_HOST_TEST=${{ secrets.DB_HOST_TEST }}" >> .env
          echo "POSTGRES_PORT_TEST=${{ secrets.DB_PORT_TEST }}" >> .env

          echo "# JWT Token" >> .env
          echo "ACCESS_TOKEN_KEY=${{ secrets.APP_ACCESS_TOKEN_KEY }}" >> .env
          echo "REFRESH_TOKEN_KEY=${{ secrets.APP_REFRESH_TOKEN_KEY }}" >> .env
          echo "ACCCESS_TOKEN_AGE=${{ secrets.APP_ACCCESS_TOKEN_AGE }}" >> .env

      - name: Build and Run Container
        run: |
          sudo docker compose up --build --detach

      - name: Hit Endpoint
        run: |
          sleep 20
          curl ${{ vars.DEV_URL }}
