name: Forum API CI (Docker Compose with RDS)

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file for application runtime
        run: |
          echo "NODE_ENV=test" > .env
          echo "PGHOST_TEST=${{ secrets.DB_HOST_TEST }}" >> .env
          echo "PGPORT_TEST=${{ secrets.DB_PORT_TEST }}" >> .env
          echo "PGUSER_TEST=${{ secrets.DB_USER_TEST }}" >> .env
          echo "PGPASSWORD_TEST=${{ secrets.DB_PASSWORD_TEST }}" >> .env
          echo "PGDATABASE_TEST=${{ vars.DB_DBNAME_TEST }}" >> .env
          echo "ACCESS_TOKEN_KEY=${{ secrets.APP_ACCESS_TOKEN_KEY }}" >> .env
          echo "REFRESH_TOKEN_KEY=${{ secrets.APP_REFRESH_TOKEN_KEY }}" >> .env
          echo "ACCESS_TOKEN_AGE=${{ secrets.APP_ACCCESS_TOKEN_AGE }}" >> .env
          echo "HOST=${{vars.DEV_URL}}"
          echo "PORT=${{secrets.APP_PORT}}" >> .env

      - name: Create database migration config file for test
        run: |
          mkdir -p config/database
          echo '{' > config/database/test.json
          echo '  "user": "${{ secrets.DB_USER_TEST }}",' >> config/database/test.json
          echo '  "password": "${{ secrets.DB_PASSWORD_TEST }}",' >> config/database/test.json
          echo '  "host": "${{ secrets.DB_HOST_TEST }}",' >> config/database/test.json
          echo '  "port": ${{ secrets.DB_PORT_TEST }},' >> config/database/test.json
          echo '  "database": "${{ vars.DB_DBNAME_TEST }}"' >> config/database/test.json
          echo '}' >> config/database/test.json

      - name: Build Docker images
        run: docker-compose build api

      - name: Run database migrations for test environment (on RDS)
        run: docker-compose run --rm api npm run migrate:test

      - name: Run tests (Unit, Integration, Functional)
        run: docker-compose run --rm api npm run test
