name: Forum API CI (Docker Compose with RDS)

on:
  pull_request:
    branches: ["main"]

jobs:
  build-testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "# HTTP SERVER" > .env
          echo "HOST=${{ vars.DEV_URL }}" >> .env
          echo "PORT=${{ secrets.APP_PORT }}" >> .env

          echo "# Database Production" >> .env
          echo "POSTGRES_USER=${{ secrets.DB_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.DB_DBNAME }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.DB_PORT }}" >> .env

          echo "# Database Test"
          echo "POSTGRES_USER_TEST=${{ secrets.DB_USER_TEST }}" >> .env
          echo "POSTGRES_PASSWORD_TEST=${{ secrets.DB_PASSWORD_TEST }}" >> .env
          echo "POSTGRES_DB_TEST=${{ vars.DB_DBNAME_TEST }}" >> .env
          echo "POSTGRES_HOST_TEST=${{ secrets.DB_HOST_TEST }}" >> .env
          echo "POSTGRES_PORT_TEST=${{ secrets.DB_PORT_TEST }}" >> .env

          echo "# JWT Token" >> .env
          echo "ACCESS_TOKEN_KEY=${{ secrets.APP_ACCESS_TOKEN_KEY }}" >> .env
          echo "REFRESH_TOKEN_KEY=${{ secrets.APP_REFRESH_TOKEN_KEY }}" >> .env
          echo "ACCCESS_TOKEN_AGE=${{ secrets.APP_ACCCESS_TOKEN_AGE }}" >> .env

      - name: Create database migration config file for test
        run: |
          mkdir -p config/database
          echo '{' > config/database/test.json
          echo '  "user": "${{ secrets.DB_USER_TEST }}",' >> config/database/test.json
          echo '  "password": "${{ secrets.DB_PASSWORD_TEST }}",' >> config/database/test.json
          echo '  "host": "${{ secrets.DB_HOST_TEST }}",' >> config/database/test.json
          echo '  "port": ${{ secrets.DB_PORT_TEST }},' >> config/database/test.json
          echo '  "database": "${{ vars.DB_DBNAME_TEST }}"' >> config/database/test.json
          echo '}' >> config/database/test.json

      - name: Build and Run Container
        run: |
          sudo docker compose up --build --detach

      - name: Run tests (Unit, Integration, Functional)
        run: |
          sudo docker exec forum-api bash -c "npm run test"
